### ISSUE TITLE
文章内容乱码

### ISSUE THREAD

**Issue by Issac-Newton** [linuxkerneltravel/website#28]
linux内核之旅 网站 “电子杂志” 里面 《i386体系结构》 文章乱码

**Comment by ljrcore** [comment]
> linux内核之旅 网站 “电子杂志” 里面 《i386体系结构》 文章乱码

感谢您的反馈，该文章目前是链接到旧网站的，正在迁移到新网站，到时会重新排版，就不会出现乱码。
目前的解决方案是您可以更改网页编码方式，使用utf-8格式进行查看，就不会有乱码了。
