### ISSUE TITLE
部分css，js文件本地化，加速网站加载

### ISSUE THREAD

**Issue by helight** [linuxkerneltravel/website#35]
目前发现这些css，js文件加载速度较慢，需要优化，方式有2种：
1.迁移到站点内部
2.寻找国内合适免费的cdn来存放

大家看看怎么好处理

为避免重复，有想翻译的，直接在issue中回复认领就可以了哈

https://use.fontawesome.com/releases/v5.11.2/css/all.css
http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

http://code.jquery.com/jquery-3.1.1.min.js
https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js
https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0/jquery.counterup.min.js
https://cdnjs.cloudflare.com/ajax/libs/jquery-parallax/1.1.3/jquery-parallax.js

**Comment by szp2016** [comment]
认领一下，修改为国内猫云cdn，速度会有改善。

**Comment by szp2016** [comment]
我改一下js和css，使用国内猫云cdn，速度会有提升。

**Comment by helight** [comment]
👍

**Comment by helight** [comment]
应合并了，css和js的访问速度提升非常明显。
