### ISSUE TITLE
网站带有子菜单的按钮都不可用了，希望继续维护呀

### ISSUE THREAD

**Issue by LoserJL** [linuxkerneltravel/website#40]
如题

**Comment by ljrcore** [comment]
> 如题

经过测试，可以使用的，请更换浏览器后重试，测试浏览器：
- Firefox Browser 76.0.1 (64 位)
- Google Chrome  80.0.3987.162（正式版本） （64 位）

**Comment by chenamy2017** [comment]
经过我测试，子菜单也无法打开：
系统：Windows 10 企业版
浏览器：Google Chrome  版本 87.0.4280.88（正式版本） （64 位）

**Comment by helight** [comment]
我先再打开，估计和css和js的加载有关系。
@chenamy2017 f12看看浏览器的css和js是不是全部加载正常了。

**Comment by chenamy2017** [comment]
今天打开一切正常，子菜单可以打开，问题应该是已经解决了。

**Comment by j1angle0** [comment]
已经正常了，谢谢，谢谢，谢谢
