### ISSUE TITLE
关于投稿微信公众号

### ISSUE THREAD

**Issue by LeiZhang-Hunter** [linuxkerneltravel/website#78]
你好我们是擎创科技：
公司官网:
https://www.eoitek.com/
我们在ebpf 领域 进行了半年探索，希望把沉淀的一些技术点贡献给社区，请问该如何给公众号投稿

**Comment by helight** [comment]
可以微信联系 helightx




七度黑光
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linuxkerneltravel/website"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月5日(星期三) 下午2:38
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[linuxkerneltravel/website] 关于投稿微信公众号 (Issue #78)





 
你好我们是擎创科技：
 公司官网:
 https://www.eoitek.com/
 我们在ebpf 领域 进行了半年探索，希望把沉淀的一些技术点贡献给社区，请问该如何给公众号投稿
